import {QUESTION_EXAMPLES} from './question-examples.js';
// 운영 화면에서 선별한 자료 메타데이터 30개(DB18+문항12) + 교재 DB 예시 18개(sample:true, 실제 상품 아님, 2026-09-27). 계정/쿠키/세션 정보 없음.
export const grades = ["중1","중2","중3","고1","고2","고3"];
export const dbs = [
  {
    "id": "school-225416",
    "kind": "school",
    "title": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "grade": "중1",
    "school": "서울여중",
    "schoolFullName": "서울여자중학교",
    "region": "서울시",
    "district": "마포구",
    "year": 2023,
    "semester": "1학기",
    "exam": "중간",
    "subject": "중등수학1상",
    "count": 28,
    "avg": 4.1,
    "bins": [
      5,
      16,
      7,
      0
    ],
    "price": null,
    "originalPrice": null,
    "status": "이용 가능",
    "range": "중1-1: 소인수분해, 최대공약수와 최소공배수, 정수와 유리수, 정수와 유리수의 계산",
    "publisher": "",
    "preview": null,
    "questionIds": [
      "q1109861",
      "q1109862",
      "q1109863",
      "q1109864",
      "q1109865",
      "q1109866",
      "q1109868",
      "q1109869",
      "q1109872"
    ],
    "explanation": "미확인",
    "format": "DB Pro",
    "sourceEvidence": "live-middle1.html 실제 DB225416, 총28문항 중9개 표본",
    "rentalEligible": true
  },
  {
    "id": "school-0",
    "kind": "school",
    "title": "내신 2026년 경기 용인시 서원고 고2 공통 2학기 중간 기하",
    "grade": "고2",
    "school": "서원고",
    "region": "경기",
    "district": "용인시",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "기하",
    "count": 21,
    "avg": 4.0,
    "bins": [
      1,
      14,
      6,
      0
    ],
    "price": 9450,
    "originalPrice": 18900,
    "status": "DB화 진행 중",
    "range": "기하: 01 포물선 - 05 공간도형",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 0",
    "rentalEligible": true
  },
  {
    "id": "school-1",
    "kind": "school",
    "title": "내신 2026년 경기 용인시 서원중 중2 2학기 중간 중등수학2하",
    "grade": "중2",
    "school": "서원중",
    "region": "경기",
    "district": "용인시",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "중등수학2하",
    "count": 22,
    "avg": 4.2,
    "bins": [
      1,
      16,
      5,
      0
    ],
    "price": 7450,
    "originalPrice": 14900,
    "status": "DB화 진행 중",
    "range": "중2-2: 01 이등변삼각형과 직각삼각형 - 06 평행선과 선분의 길이의 비, 08 닮은 도형의 넓이와 부피",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 1",
    "rentalEligible": true
  },
  {
    "id": "school-2",
    "kind": "school",
    "title": "내신 2026년 충북 청주시 가경중 중1 1학기 중간 중등수학1상",
    "grade": "중1",
    "school": "가경중",
    "region": "충북",
    "district": "청주시",
    "year": 2026,
    "semester": "1학기",
    "exam": "중간",
    "subject": "중등수학1상",
    "count": 22,
    "avg": 3.8,
    "bins": [
      3,
      17,
      2,
      0
    ],
    "price": 6100,
    "originalPrice": 12200,
    "status": "DB화 진행 중",
    "range": "중1-1: 01 소인수분해 - 05 문자와 식",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 2",
    "rentalEligible": true
  },
  {
    "id": "school-3",
    "kind": "school",
    "title": "내신 2026년 울산시 동구 대송고 고1 공통 2학기 중간 공통수학2",
    "grade": "고1",
    "school": "대송고",
    "region": "울산시",
    "district": "동구",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "공통수학2",
    "count": 18,
    "avg": 4.2,
    "bins": [
      1,
      11,
      6,
      0
    ],
    "price": 7600,
    "originalPrice": 15200,
    "status": "DB화 진행 중",
    "range": "공통수학2: 02 직선의 방정식 - 06 집합의 연산",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 3",
    "rentalEligible": true
  },
  {
    "id": "school-4",
    "kind": "school",
    "title": "내신 2026년 울산시 동구 대송고 고2 공통 2학기 중간 미적분1",
    "grade": "고2",
    "school": "대송고",
    "region": "울산시",
    "district": "동구",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "미적분1",
    "count": 21,
    "avg": 4.0,
    "bins": [
      3,
      13,
      4,
      1
    ],
    "price": 9700,
    "originalPrice": 19400,
    "status": "DB화 진행 중",
    "range": "미적분1: 01 함수의 극한 - 04 접선의 방정식",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 4",
    "rentalEligible": true
  },
  {
    "id": "school-5",
    "kind": "school",
    "title": "내신 2026년 경기 용인시 성복중 중3 2학기 중간 중등수학3하",
    "grade": "중3",
    "school": "성복중",
    "region": "경기",
    "district": "용인시",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "중등수학3하",
    "count": 21,
    "avg": 4.4,
    "bins": [
      2,
      10,
      9,
      0
    ],
    "price": 6800,
    "originalPrice": 13600,
    "status": "DB화 진행 중",
    "range": "중3-1: 07 근의 공식과 이차방정식의 활용중3-2: 01 삼각비 - 03 원과 직선",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 5",
    "rentalEligible": true
  },
  {
    "id": "school-11",
    "kind": "school",
    "title": "내신 2026년 경기 성남시 분당중앙고 고3 공통 1학기 중간 미적분",
    "grade": "고3",
    "school": "분당중앙고",
    "region": "경기",
    "district": "성남시",
    "year": 2026,
    "semester": "1학기",
    "exam": "중간",
    "subject": "미적분",
    "count": 20,
    "avg": 4.9,
    "bins": [
      1,
      9,
      8,
      2
    ],
    "price": 8800,
    "originalPrice": 17600,
    "status": "DB화 진행 중",
    "range": "미적분2: 01 수열의 극한 - 07 여러 가지 미분법, 10 방부등식에의 활용과 평면운동",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 11",
    "rentalEligible": true
  },
  {
    "id": "school-13",
    "kind": "school",
    "title": "내신 2026년 경기 용인시 서원고 고2 공통 2학기 중간 미적분1",
    "grade": "고2",
    "school": "서원고",
    "region": "경기",
    "district": "용인시",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "미적분1",
    "count": 21,
    "avg": 4.4,
    "bins": [
      0,
      11,
      10,
      0
    ],
    "price": 12950,
    "originalPrice": 18500,
    "status": "이용 가능",
    "range": "미적분1: 01 함수의 극한 - 05 함수의 증가와 감소",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 13",
    "rentalEligible": true
  },
  {
    "id": "school-14",
    "kind": "school",
    "title": "내신 2026년 경기 용인시 대지고 고3 공통 1학기 중간 확률과통계",
    "grade": "고3",
    "school": "대지고",
    "region": "경기",
    "district": "용인시",
    "year": 2026,
    "semester": "1학기",
    "exam": "중간",
    "subject": "확률과통계",
    "count": 20,
    "avg": 4.2,
    "bins": [
      2,
      9,
      9,
      0
    ],
    "price": 8700,
    "originalPrice": 17400,
    "status": "DB화 진행 중",
    "range": "확률과 통계: 01 여러가지순열 - 05 조건부 확률",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 14",
    "rentalEligible": true
  },
  {
    "id": "school-18",
    "kind": "school",
    "title": "내신 2026년 서울시 도봉구 창일중 중1 2학기 중간 중등수학1하",
    "grade": "중1",
    "school": "창일중",
    "region": "서울시",
    "district": "도봉구",
    "year": 2026,
    "semester": "2학기",
    "exam": "중간",
    "subject": "중등수학1하",
    "count": 26,
    "avg": 4.1,
    "bins": [
      4,
      15,
      7,
      0
    ],
    "price": 8150,
    "originalPrice": 16300,
    "status": "DB화 진행 중",
    "range": "중1-1: 04 정수와 유리수의 계산, 08 좌표평면과 그래프 - 09 정비례와 반비례중1-2: 01 기본 도형 - 02 위치 관계",
    "publisher": "",
    "preview": null,
    "questionIds": [],
    "explanation": "해설 없음",
    "format": "DB Pro",
    "sourceEvidence": "live-school.html table row 18",
    "rentalEligible": true
  },
  {
    "id": "school-simseok-2025",
    "kind": "school",
    "title": "내신 2025년 경기 남양주시 심석고 고1 공통 2학기 중간 공통수학2",
    "grade": "고1",
    "school": "심석고",
    "region": "경기",
    "district": "남양주시",
    "year": 2025,
    "semester": "2학기",
    "exam": "중간",
    "subject": "공통수학2",
    "count": 20,
    "avg": null,
    "bins": [],
    "price": null,
    "originalPrice": null,
    "status": "이용 가능",
    "range": "공통수학2: 평면좌표, 직선의 방정식 (저장 화면에서 확인한 범위)",
    "publisher": "",
    "preview": null,
    "questionIds": [
      "q4901149",
      "q4901137",
      "q4901148"
    ],
    "explanation": "미확인",
    "format": "DB Pro",
    "sourceEvidence": "live-paper.html, 검색결과20개 및 문제 이미지3개",
    "rentalEligible": true
  },
  {
    "id": "book-1685046",
    "kind": "book",
    "title": "2026년 수비프레스 B2베이직 교과서 대비 미적분2(비상)",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "미적분2",
    "count": 420,
    "avg": 4.2,
    "bins": [
      0,
      340,
      80,
      0
    ],
    "price": 210000,
    "originalPrice": 420000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수비프레스",
    "preview": "assets/books/book-1685046.webp",
    "questionIds": [],
    "explanation": "해설 420개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1685046",
    "gradeEvidence": "미적분2 과목의 고3 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  },
  {
    "id": "book-1685045",
    "kind": "book",
    "title": "2026년 수비프레스 B2베이직 교과서 대비 미적분2(천재)",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "미적분2",
    "count": 334,
    "avg": 4.2,
    "bins": [
      0,
      260,
      74,
      0
    ],
    "price": 167000,
    "originalPrice": 334000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수비프레스",
    "preview": "assets/books/book-1685045.webp",
    "questionIds": [],
    "explanation": "해설 334개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1685045",
    "gradeEvidence": "미적분2 과목의 고3 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  },
  {
    "id": "book-1685044",
    "kind": "book",
    "title": "2026년 수비프레스 B2베이직 교과서 대비 미적분2(미래엔)",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "미적분2",
    "count": 360,
    "avg": 4.3,
    "bins": [
      0,
      280,
      80,
      0
    ],
    "price": 180000,
    "originalPrice": 360000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수비프레스",
    "preview": "assets/books/book-1685044.webp",
    "questionIds": [],
    "explanation": "해설 360개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1685044",
    "gradeEvidence": "미적분2 과목의 고3 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  },
  {
    "id": "book-1684137",
    "kind": "book",
    "title": "2026년 씨에스엠17 고2 9월 모의고사 변형",
    "grade": "고2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "모의고사",
    "subject": "수학",
    "count": 56,
    "avg": 5.7,
    "bins": [
      0,
      0,
      52,
      4
    ],
    "price": 250000,
    "originalPrice": 250000,
    "status": "이용 가능",
    "range": "",
    "publisher": "씨에스엠17",
    "preview": "assets/books/book-1684137.webp",
    "questionIds": [],
    "explanation": "해설 56개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1684137",
    "gradeEvidence": "제목 확인",
    "rentalEligible": true
  },
  {
    "id": "book-1684136",
    "kind": "book",
    "title": "2026년 씨에스엠17 고3 9월 모의고사 변형",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "모의고사",
    "subject": "수학",
    "count": 60,
    "avg": 5.7,
    "bins": [
      0,
      6,
      39,
      15
    ],
    "price": 600000,
    "originalPrice": 600000,
    "status": "이용 가능",
    "range": "",
    "publisher": "씨에스엠17",
    "preview": "assets/books/book-1684136.webp",
    "questionIds": [],
    "explanation": "해설 60개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1684136",
    "gradeEvidence": "제목 확인",
    "rentalEligible": true
  },
  {
    "id": "book-1684135",
    "kind": "book",
    "title": "2026년 씨에스엠17 고1 9월 모의고사 변형",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "모의고사",
    "subject": "수학",
    "count": 56,
    "avg": 5.7,
    "bins": [
      0,
      8,
      39,
      9
    ],
    "price": 200000,
    "originalPrice": 200000,
    "status": "이용 가능",
    "range": "",
    "publisher": "씨에스엠17",
    "preview": "assets/books/book-1684135.webp",
    "questionIds": [],
    "explanation": "해설 56개",
    "format": "교재 DB",
    "sourceEvidence": "live-books.html public product 1684135",
    "gradeEvidence": "제목 확인",
    "rentalEligible": true
  },
  {
    "id": "book-sample-01",
    "kind": "book",
    "title": "2026 SYNC 모의고사 고1 3월 대비 1회",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "공통수학1",
    "count": 160,
    "avg": 3.9,
    "bins": [
      15,
      63,
      23,
      59
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "SYNC모의고사",
    "preview": "assets/books/book-sample-01.svg",
    "questionIds": [],
    "explanation": "해설 160개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "공통수학1 과목의 고1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-02",
    "kind": "book",
    "title": "2026 SYNC 모의고사 고2 6월 대비 2회",
    "grade": "고2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "대수",
    "count": 240,
    "avg": 4.1,
    "bins": [
      23,
      86,
      39,
      92
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "SYNC모의고사",
    "preview": "assets/books/book-sample-02.svg",
    "questionIds": [],
    "explanation": "해설 240개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "대수 과목의 고2 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-03",
    "kind": "book",
    "title": "2026 SYNC 모의고사 고3 9월 대비 3회",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "미적분2",
    "count": 320,
    "avg": 4.0,
    "bins": [
      29,
      124,
      56,
      111
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "SYNC모의고사",
    "preview": "assets/books/book-sample-03.svg",
    "questionIds": [],
    "explanation": "해설 320개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "미적분2 과목의 고3 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-04",
    "kind": "book",
    "title": "아름다운샘 개념 완성 중1-2",
    "grade": "중1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 360,
    "avg": 4.1,
    "bins": [
      34,
      168,
      85,
      73
    ],
    "price": 210000,
    "originalPrice": 420000,
    "status": "이용 가능",
    "range": "",
    "publisher": "아름다운샘",
    "preview": "assets/books/book-sample-04.svg",
    "questionIds": [],
    "explanation": "해설 360개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-05",
    "kind": "book",
    "title": "아름다운샘 유형 완성 중2-2",
    "grade": "중2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 120,
    "avg": 4.1,
    "bins": [
      16,
      44,
      17,
      43
    ],
    "price": 150000,
    "originalPrice": 300000,
    "status": "이용 가능",
    "range": "",
    "publisher": "아름다운샘",
    "preview": "assets/books/book-sample-05.svg",
    "questionIds": [],
    "explanation": "해설 120개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중2 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-06",
    "kind": "book",
    "title": "아름다운샘 실력 완성 공통수학1",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "공통수학1",
    "count": 360,
    "avg": 3.9,
    "bins": [
      27,
      127,
      72,
      134
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "아름다운샘",
    "preview": "assets/books/book-sample-06.svg",
    "questionIds": [],
    "explanation": "해설 360개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "공통수학1 과목의 고1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-07",
    "kind": "book",
    "title": "모킹버드 내신 대비 중3-2 1회",
    "grade": "중3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 280,
    "avg": 4.0,
    "bins": [
      2,
      137,
      60,
      81
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "모킹버드",
    "preview": "assets/books/book-sample-07.svg",
    "questionIds": [],
    "explanation": "해설 280개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중3 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-08",
    "kind": "book",
    "title": "모킹버드 내신 대비 공통수학2",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "공통수학2",
    "count": 200,
    "avg": 4.0,
    "bins": [
      20,
      67,
      30,
      83
    ],
    "price": 180000,
    "originalPrice": 360000,
    "status": "이용 가능",
    "range": "",
    "publisher": "모킹버드",
    "preview": "assets/books/book-sample-08.svg",
    "questionIds": [],
    "explanation": "해설 200개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "공통수학2 과목의 고1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-09",
    "kind": "book",
    "title": "모킹버드 내신 대비 미적분1",
    "grade": "고2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "미적분1",
    "count": 160,
    "avg": 3.9,
    "bins": [
      4,
      56,
      26,
      74
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "모킹버드",
    "preview": "assets/books/book-sample-09.svg",
    "questionIds": [],
    "explanation": "해설 160개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "미적분1 과목의 고2 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-10",
    "kind": "book",
    "title": "수심달 기본 중1-2",
    "grade": "중1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 280,
    "avg": 5.2,
    "bins": [
      33,
      97,
      38,
      112
    ],
    "price": 210000,
    "originalPrice": 420000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수심달 (NE능률)",
    "preview": "assets/books/book-sample-10.svg",
    "questionIds": [],
    "explanation": "해설 280개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-11",
    "kind": "book",
    "title": "수심달 심화 중2-2",
    "grade": "중2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 120,
    "avg": 4.3,
    "bins": [
      14,
      60,
      16,
      30
    ],
    "price": 250000,
    "originalPrice": 500000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수심달 (NE능률)",
    "preview": "assets/books/book-sample-11.svg",
    "questionIds": [],
    "explanation": "해설 120개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중2 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-12",
    "kind": "book",
    "title": "수심달 실전 확률과통계",
    "grade": "고2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "확률과통계",
    "count": 160,
    "avg": 5.3,
    "bins": [
      26,
      67,
      38,
      29
    ],
    "price": 210000,
    "originalPrice": 420000,
    "status": "이용 가능",
    "range": "",
    "publisher": "수심달 (NE능률)",
    "preview": "assets/books/book-sample-12.svg",
    "questionIds": [],
    "explanation": "해설 160개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "확률과통계 과목의 고2 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-13",
    "kind": "book",
    "title": "봉샘스쿨 개념 특강 중3-2",
    "grade": "중3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 120,
    "avg": 4.8,
    "bins": [
      16,
      46,
      22,
      36
    ],
    "price": 180000,
    "originalPrice": 360000,
    "status": "이용 가능",
    "range": "",
    "publisher": "봉샘스쿨",
    "preview": "assets/books/book-sample-13.svg",
    "questionIds": [],
    "explanation": "해설 120개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중3 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-14",
    "kind": "book",
    "title": "봉샘스쿨 유형 특강 공통수학1",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "공통수학1",
    "count": 200,
    "avg": 5.2,
    "bins": [
      13,
      77,
      36,
      74
    ],
    "price": 210000,
    "originalPrice": 420000,
    "status": "이용 가능",
    "range": "",
    "publisher": "봉샘스쿨",
    "preview": "assets/books/book-sample-14.svg",
    "questionIds": [],
    "explanation": "해설 200개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "공통수학1 과목의 고1 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-15",
    "kind": "book",
    "title": "봉샘스쿨 기출 특강 기하",
    "grade": "고3",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "기하",
    "count": 320,
    "avg": 4.5,
    "bins": [
      9,
      111,
      47,
      153
    ],
    "price": 150000,
    "originalPrice": 300000,
    "status": "이용 가능",
    "range": "",
    "publisher": "봉샘스쿨",
    "preview": "assets/books/book-sample-15.svg",
    "questionIds": [],
    "explanation": "해설 320개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "기하 과목의 고3 분류",
    "rentalEligible": true
  },
  {
    "id": "book-sample-16",
    "kind": "book",
    "title": "2022 개정 교과서 중1 수학 교사용 문항",
    "grade": "중1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "수학",
    "count": 200,
    "avg": 5.3,
    "bins": [
      29,
      70,
      40,
      61
    ],
    "price": 90000,
    "originalPrice": 180000,
    "status": "이용 가능",
    "range": "",
    "publisher": "교과서 또는 교사용",
    "preview": "assets/books/book-sample-16.svg",
    "questionIds": [],
    "explanation": "해설 200개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "수학 과목의 중1 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  },
  {
    "id": "book-sample-17",
    "kind": "book",
    "title": "2022 개정 교과서 공통수학1 교사용 문항",
    "grade": "고1",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "공통수학1",
    "count": 320,
    "avg": 5.0,
    "bins": [
      45,
      146,
      67,
      62
    ],
    "price": 250000,
    "originalPrice": 500000,
    "status": "이용 가능",
    "range": "",
    "publisher": "교과서 또는 교사용",
    "preview": "assets/books/book-sample-17.svg",
    "questionIds": [],
    "explanation": "해설 320개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "공통수학1 과목의 고1 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  },
  {
    "id": "book-sample-18",
    "kind": "book",
    "title": "2022 개정 교과서 대수 교사용 문항",
    "grade": "고2",
    "school": "",
    "region": "",
    "district": "",
    "year": 2026,
    "semester": "",
    "exam": "교재",
    "subject": "대수",
    "count": 240,
    "avg": 5.2,
    "bins": [
      27,
      100,
      42,
      71
    ],
    "price": 180000,
    "originalPrice": 360000,
    "status": "이용 가능",
    "range": "",
    "publisher": "교과서 또는 교사용",
    "preview": "assets/books/book-sample-18.svg",
    "questionIds": [],
    "explanation": "해설 240개",
    "format": "교재 DB",
    "sourceEvidence": "예시 데이터 — 실제 상품 아님 (사용자 요청 2026-09-27: 빈 브랜드 폴더에 동작 확인용 표본)",
    "sample": true,
    "gradeEvidence": "대수 과목의 고2 분류",
    "rentalEligible": false,
    "rentalExclusionReason": "교과서/교사용·프리미엄 자료는 DB 구독 대상에서 제외됩니다."
  }
];

export const questions = [
  {
    "id": "q4901149",
    "dbId": "school-simseok-2025",
    "grade": "고1",
    "number": 20,
    "title": "03 삼각형 관련정리3 (내각의 이등분선)",
    "text": "양수 a에 대하여 그림과 같이 세 점 A(0, a), B(-4, 0), C(6, 0)을 꼭짓점으로 하는 삼각형 ABC가 있다. y절편이 2이고 ∠ABC를 이등분하는 직선이 선분 AC와 만나는 점을 D라 하자. 삼각형 ABD의 넓이를 S라 할 때, 6S의 값은?",
    "formula": "A(0,a) B(-4,0) C(6,0) 6S",
    "choices": [
      "56",
      "60",
      "64",
      "68",
      "72"
    ],
    "image": "assets/questions/q4901149.png",
    "answer": null,
    "solution": null,
    "difficulty": 5,
    "answerType": "객관식",
    "unit": "08 공통수학2 > 01 평면좌표 > 02 내분점 > 05 내분점5 (삼각형 관련정리) > 03 삼각형 관련정리3 (내각의 이등분선)",
    "tags": [
      "01 평면좌표",
      "02 내분점",
      "05 내분점5 (삼각형 관련정리)",
      "03 삼각형 관련정리3 (내각의 이등분선)"
    ],
    "similarity": "same",
    "sourceTitle": "내신 2025년 경기 남양주시 심석고 고1 공통 2학기 중간 공통수학2",
    "subject": "공통수학2",
    "year": 2025,
    "sourceEvidence": "live-paper.html visible question card",
    "minutes": 5
  },
  {
    "id": "q4901137",
    "dbId": "school-simseok-2025",
    "grade": "고1",
    "number": 8,
    "title": "06 추론과 해석6 (직선 위의 점과의 길이비. 분점의 위치 조건)",
    "text": "두 점 A(2, 5), B(-6, 1)에 대하여 두 점 A, B를 지나는 직선 위에 있고 AB=2BC를 만족하는 모든 점 C의 좌표가 (a, b), (c, d)일 때, a+b+c+d의 값은?",
    "formula": "A(2,5) B(-6,1) AB=2BC a+b+c+d",
    "choices": [
      "-10",
      "-12",
      "-14",
      "-16",
      "-18"
    ],
    "image": "assets/questions/q4901137.png",
    "answer": null,
    "solution": null,
    "difficulty": 5,
    "answerType": "객관식",
    "unit": "08 공통수학2 > 01 평면좌표 > 02 내분점 > 07 내분점7 (추론과 해석) > 06 추론과 해석6 (직선 위의 점과의 길이비. 분점의 위치 조건)",
    "tags": [
      "01 평면좌표",
      "02 내분점",
      "07 내분점7 (추론과 해석)",
      "06 추론과 해석6 (직선 위의 점과의 길이비. 분점의 위치 조건)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2025년 경기 남양주시 심석고 고1 공통 2학기 중간 공통수학2",
    "subject": "공통수학2",
    "year": 2025,
    "sourceEvidence": "live-paper.html visible question card",
    "minutes": 5
  },
  {
    "id": "q4901148",
    "dbId": "school-simseok-2025",
    "grade": "고1",
    "number": 19,
    "title": "01 제곱의 합의 Mm1 (수직선 또는 직선 위의 점 조건)",
    "text": "정삼각형 ABC의 변 BC 위의 P에 대하여 PA²+PC²의 값은 점 P₁에 있을 때 최솟값을 갖는다. 삼각형 AP₁C의 넓이가 9√3일 때, 삼각형 ABP₁의 넓이는? (단, 점 P는 양 끝점이 아니다)",
    "formula": "PA^2+PC^2 9sqrt(3) 9√3",
    "choices": [
      "15√3",
      "18√3",
      "21√3",
      "24√3",
      "27√3"
    ],
    "image": "assets/questions/q4901148.png",
    "answer": null,
    "solution": null,
    "difficulty": 6,
    "answerType": "객관식",
    "unit": "08 공통수학2 > 01 평면좌표 > 03 평면좌표의 활용 > 01 활용1 (제곱의 합의 Mm) > 01 제곱의 합의 Mm1 (수직선 또는 직선 위의 점 조건)",
    "tags": [
      "01 평면좌표",
      "03 평면좌표의 활용",
      "01 활용1 (제곱의 합의 Mm)",
      "01 제곱의 합의 Mm1 (수직선 또는 직선 위의 점 조건)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2025년 경기 남양주시 심석고 고1 공통 2학기 중간 공통수학2",
    "subject": "공통수학2",
    "year": 2025,
    "sourceEvidence": "live-paper.html visible question card",
    "minutes": 10
  },
  {
    "id": "q1109861",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 1,
    "title": "02 성질2 (합답형)",
    "text": "보기에서 옳은 것을 있는 대로 고른 것은? ㄱ. 2×3×3×2×7=2²×3²×7 ㄴ. 소수는 모두 홀수이다. ㄷ. 5³에서 5를 밑, 3을 지수라고 한다. ㄹ. 모든 자연수는 약수를 2개 이상 갖는다.",
    "formula": "2*3*3*2*7=2^2*3^2*7 5^3",
    "choices": [
      "ㄱ, ㄷ",
      "ㄱ, ㄹ",
      "ㄴ, ㄹ",
      "ㄱ, ㄷ, ㄹ",
      "ㄴ, ㄷ, ㄹ"
    ],
    "image": "assets/questions/q1109861.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 01 소인수분해 > 01 소수와 합성수 > 04 소수와 합성수4 (성질) > 02 성질2 (합답형)",
    "tags": [
      "소인수분해",
      "소수와 합성수",
      "소수와 합성수4 (성질)",
      "성질2 (합답형)"
    ],
    "similarity": "same",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109861",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109862",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 2,
    "title": "04 소인수분해4 (주어진 수의 소인수분해)",
    "text": "360을 소인수분해하면?",
    "formula": "360 2^2*3*5^2 2^2*3^2*10 2^2*3^3*5 2^3*3*5 2^3*3^2*5",
    "choices": [
      "2²×3×5²",
      "2²×3²×10",
      "2²×3³×5",
      "2³×3×5",
      "2³×3²×5"
    ],
    "image": "assets/questions/q1109862.png",
    "answer": null,
    "solution": null,
    "difficulty": 2,
    "answerType": "객관식",
    "unit": "01 중1-1 > 01 소인수분해 > 03 소인수의 뜻과 소인수분해 > 01 소인수분해1 (소인수분해하기) > 04 소인수분해4 (주어진 수의 소인수분해)",
    "tags": [
      "소인수분해",
      "소인수의 뜻과 소인수분해",
      "소인수분해1 (소인수분해하기)",
      "소인수분해4 (주어진 수의 소인수분해)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109862",
    "minutes": 1,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109863",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 3,
    "title": "01 소인수 구하기1 (기본)",
    "text": "보기의 자연수 중에서 소인수를 가장 적게 갖는 수를 있는 대로 고른 것은? 보기: 30, 75, 128, 162, 198",
    "formula": "30 75 128 162 198",
    "choices": [
      "30",
      "75",
      "128",
      "30, 198",
      "75, 162"
    ],
    "image": "assets/questions/q1109863.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 01 소인수분해 > 03 소인수의 뜻과 소인수분해 > 03 소인수분해3 (소인수 구하기) > 01 소인수 구하기1 (기본)",
    "tags": [
      "소인수분해",
      "소인수의 뜻과 소인수분해",
      "소인수분해3 (소인수 구하기)",
      "소인수 구하기1 (기본)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109863",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109864",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 4,
    "title": "01 약수 구하기1 (소인수분해된 자연수)",
    "text": "5²×7³×13의 약수가 아닌 것은?",
    "formula": "5^2*7^3*13",
    "choices": [
      "5²×7²",
      "5×7³",
      "5²×7×13",
      "5×7⁴×13",
      "5²×7²×13"
    ],
    "image": "assets/questions/q1109864.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 01 소인수분해 > 04 약수의 개수 > 01 약수의 개수1 (약수 구하기) > 01 약수 구하기1 (소인수분해된 자연수)",
    "tags": [
      "소인수분해",
      "약수의 개수",
      "약수의 개수1 (약수 구하기)",
      "약수 구하기1 (소인수분해된 자연수)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109864",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109865",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 5,
    "title": "01 제곱수 만들기1 (곱하는 수 구하기)",
    "text": "112에 자연수를 곱하여 어떤 자연수의 제곱이 되도록 할 때, 곱할 수 있는 자연수를 모두 고르면? (정답2개)",
    "formula": "112",
    "choices": [
      "7",
      "35",
      "49",
      "56",
      "63"
    ],
    "image": "assets/questions/q1109865.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 01 소인수분해 > 03 소인수의 뜻과 소인수분해 > 05 제곱수2 (제곱수 만들기) > 01 제곱수 만들기1 (곱하는 수 구하기)",
    "tags": [
      "소인수분해",
      "소인수의 뜻과 소인수분해",
      "제곱수2 (제곱수 만들기)",
      "제곱수 만들기1 (곱하는 수 구하기)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109865",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109866",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 6,
    "title": "03 밑과 지수3 (최대공약수와 최소공배수 조건)",
    "text": "두 수 2ᵃ×3×5와 2²×3ᵇ×c의 최대공약수는 2²×3이고, 최소공배수는 2³×3²×5×11이다. 이때 자연수 a, b, c에 대해 a-b+c의 값은? (단, c는 2, 3이 아닌 소수이다.)",
    "formula": "2^a*3*5 2^2*3^b*c 2^2*3 2^3*3^2*5*11 a-b+c",
    "choices": [
      "9",
      "12",
      "14",
      "15",
      "16"
    ],
    "image": "assets/questions/q1109866.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 02 최대공약수와 최소공배수 > 02 최소공배수 > 06 최소공배수6 (최대공약수 또는 최소공배수 조건에서 밑과 지수 구하기) > 03 밑과 지수3 (최대공약수와 최소공배수 조건)",
    "tags": [
      "최대공약수와 최소공배수",
      "최소공배수",
      "최소공배수6 (최대공약수 또는 최소공배수 조건에서 밑과 지수 구하기)",
      "밑과 지수3 (최대공약수와 최소공배수 조건)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109866",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109868",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 8,
    "title": "01 직사각형",
    "text": "가로의 길이가 154cm, 세로의 길이가 126cm인 직사각형 모양의 벽면에 크기가 같은 정사각형 모양의 타일을 빈틈없이 붙여서 타일 벽화를 완성하려고 하나 가능한 큰 타일을 사용하려고 할 때, 필요한 타일의 개수는?",
    "formula": "154 126",
    "choices": [
      "14개",
      "49개",
      "63개",
      "78개",
      "99개"
    ],
    "image": "assets/questions/q1109868.png",
    "answer": null,
    "solution": null,
    "difficulty": 2,
    "answerType": "객관식",
    "unit": "01 중1-1 > 02 최대공약수와 최소공배수 > 03 최대공약수와 최소공배수의 활용 > 02 최대공약수의 활용2 (직사각형 또는 직육면체 채우기) > 01 직사각형",
    "tags": [
      "최대공약수와 최소공배수",
      "최대공약수와 최소공배수의 활용",
      "최대공약수의 활용2 (직사각형 또는 직육면체 채우기)",
      "직사각형"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109868",
    "minutes": 1,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109869",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 9,
    "title": "01 동시 시작1 (배차 간격. 두 종류)",
    "text": "어느 터미널에서 전주행 버스는 25분, 당진행 버스는 40분 간격으로 출발한다고 한다. 오전 10시에 두 도시로 가는 버스가 동시에 출발하였을 때, 그 후에 처음으로 두 버스가 동시에 출발하는 시각은?",
    "formula": "25 40 10",
    "choices": [
      "오후 1시 20분",
      "오후 1시 40분",
      "오후 2시",
      "오후 2시 20분",
      "오후 2시 40분"
    ],
    "image": "assets/questions/q1109869.png",
    "answer": null,
    "solution": null,
    "difficulty": 2,
    "answerType": "객관식",
    "unit": "01 중1-1 > 02 최대공약수와 최소공배수 > 03 최대공약수와 최소공배수의 활용 > 05 최소공배수의 활용1 (동시에 시작해서 다시 만나는 경우) > 01 동시 시작1 (배차 간격. 두 종류)",
    "tags": [
      "최대공약수와 최소공배수",
      "최대공약수와 최소공배수의 활용",
      "최소공배수의 활용1 (동시에 시작해서 다시 만나는 경우)",
      "동시 시작1 (배차 간격. 두 종류)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109869",
    "minutes": 1,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  },
  {
    "id": "q1109872",
    "dbId": "school-225416",
    "grade": "중1",
    "number": 12,
    "title": "02 주어진 범위2 (정수 구하기)",
    "text": "-3 이상이고 8/3보다 크지 않은 정수 a는 모두 몇 개인가?",
    "formula": "-3 8/3 a",
    "choices": [
      "3개",
      "4개",
      "5개",
      "6개",
      "7개"
    ],
    "image": "assets/questions/q1109872.png",
    "answer": null,
    "solution": null,
    "difficulty": 4,
    "answerType": "객관식",
    "unit": "01 중1-1 > 03 정수와 유리수 > 03 수의 대소 관계 > 06 대소 관계6 (주어진 범위에 속하는 수) > 02 주어진 범위2 (정수 구하기)",
    "tags": [
      "정수와 유리수",
      "수의 대소 관계",
      "대소 관계6 (주어진 범위에 속하는 수)",
      "주어진 범위2 (정수 구하기)"
    ],
    "similarity": "similar",
    "sourceTitle": "내신 2023년 서울시 마포구 서울여중 중1 1학기 중간 중등수학1상",
    "subject": "중등수학1상",
    "year": 2023,
    "sourceEvidence": "live-middle1.html visible question card q1109872",
    "minutes": 3,
    "transcriptionSource": "운영 문항 PNG 육안 확인"
  }
];

// Explicit examples fill otherwise empty previews; never evidence of actual exam contents.
for (const example of QUESTION_EXAMPLES) {
  const db = dbs.find(item => item.id === example.dbId);
  if (!db) throw new Error(`Unknown example DB: ${example.dbId}`);
  // Example curriculum follows its mathematical topic, independently of the exam metadata.
  const exampleCourses = {
    'school-0':['new','기하'], 'school-1':['new','중2-2'],
    'school-2':['new','중1-1'], 'school-3':['new','공통수학2'],
    'school-4':['new','미적분1'], 'school-5':['new',example.topic==='이차방정식'?'중3-1':'중3-2'],
    'school-11':['old','미적'], 'school-13':['new','미적분1'],
    'school-14':['old','확통'], 'school-18':['new','중1-1']
  };
  const [curriculum,course] = exampleCourses[example.dbId];
  questions.push({...example, grade:db.grade, subject:db.subject, year:db.year, curriculum,
    sourceTitle:`${db.grade} ${db.subject} 예시 문항`,
    sourceEvidence:'프로토타입에서 만든 예시이며 해당 학교의 실제 시험 문항이 아닙니다.',
    unit:`${course} > ${example.topic}`, tags:[example.topic], minutes:3});
  db.questionIds.push(example.id);
  db.previewExample = true;
}

// The prototype bank reuses these sampled questions; their verified original DB source is unchanged.
// This flag describes the demo catalog, not membership in the operating service's problem bank.
for (const question of questions) {
  question.availableInBank = true;
  question.bankSample = true;
}
