import {renderNumericQuestionImage} from './numeric-masks.js';
export const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money = n => n==null ? '가격 정보 없음' : Number(n).toLocaleString('ko-KR')+'원';
const paths={'chevron-left':'m15 5-7 7 7 7','chevron-up':'m5 15 7-7 7 7','chevron-down':'m5 9 7 7 7-7',file:'M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',close:'m6 6 12 12M6 18 18 6',plus:'M12 5v14M5 12h14',chevron:'m9 5 7 7-7 7',down:'m5 9 7 7 7-7',star:'m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z',lock:'M7 11V7a5 5 0 0 1 10 0v4M5 11h14v10H5zM12 15v3',check:'m5 12 4 4L19 6',filter:'M3 5h18M6 12h12M9 19h6',arrow:'M19 12H5m6-6-6 6 6 6',monitor:'M3 4h18v13H3zM8 21h8m-4-4v4'};
const nav={search:'search',db:'db',bank:'book',paper:'book',bell:'notification',school:'school',book:'book',source:'inspect',user:'users',folder:'db'};
export function icon(name){return paths[name]?`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`:`<img class="icon" src="assets/icons/icon_${nav[name]||name}.svg" alt="">`;}
let previousFocus=null;
export function closeModal(){const el=document.querySelector('#modal-root dialog');if(el){el.close();el.remove();}previousFocus?.focus?.();}
export function openModal({title,body,footer='',wide=false,onMount}){closeModal();previousFocus=document.activeElement;const root=document.querySelector('#modal-root');root.innerHTML=`<dialog class="modal ${wide?'wide':''}" aria-labelledby="modal-title"><header><h2 id="modal-title">${esc(title)}</h2><button class="icon-btn" data-close aria-label="닫기">${icon('close')}</button></header><div class="modal-body">${body}</div>${footer?`<footer>${footer}</footer>`:''}</dialog>`;const d=root.firstElementChild;d.querySelector('[data-close]').onclick=closeModal;d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});d.addEventListener('cancel',e=>{e.preventDefault();closeModal();});d.showModal();onMount?.(d);return d;}
export function toast(text){const el=document.createElement('div');el.className='toast';el.textContent=text;document.querySelector('#toasts').append(el);setTimeout(()=>el.remove(),3800);}
export function questionCard(q,{store,source='db',selectable=false,selected=false}={}){const locked=!store.canUseQuestion(q.id,source);const expired=store.getState().subscriptions[source==='bank'?'bank':'db'].status==='expired';return `<article class="question-card ${selected?'selected':''}" data-question="${esc(q.id)}"><header>${selectable?`<label class="checkbox"><input type="checkbox" data-qcheck="${esc(q.id)}" aria-label="${q.number}번 문항 선택" ${selected?'checked':''}></label>`:''}<strong>${String(q.number).padStart(2,'0')}</strong><span>${esc(q.answerType)}</span><span class="badge">${q.sample?'예시':'Pro'}</span><span class="grow"></span><span class="muted">${esc(q.grade)} · 난이도 ${esc(q.difficulty)}</span></header><button class="question-image ${locked?'is-locked':''}" data-qopen="${esc(q.id)}" aria-label="${locked?(source==='bank'?'문항 구매 또는 구독':'구독 안내'):'문항 보기'} · ${q.number}번">${renderNumericQuestionImage(q,{locked})} </button><div class="question-meta"><span>${esc(q.unit)}</span><small>${esc(q.sourceTitle)} · ${q.number}번</small></div><footer><span class="muted">${locked?(source==='bank'?'한 문항씩 구매하거나 구독해 이용하세요.':expired?'재구독하면 담았던 문항을 다시 쓸 수 있어요.':'문제지에 담아 사용할 수 있어요.'):'여러 문항을 선택해 문제지에 담아 보세요.'}</span><button class="text-btn" data-qaction="${esc(q.id)}">${locked?(source==='bank'?'문항 구매 · 구독':'이용하기'):'문제지에 담기'} ${icon('chevron')}</button></footer></article>`;}
export function confirm({title='삭제할까요?',body='삭제한 항목은 되돌릴 수 없습니다.',button='삭제',onConfirm}){openModal({title,body:`<p>${esc(body)}</p>`,footer:`<button class="btn" data-no>취소</button><button class="btn danger" data-yes>${esc(button)}</button>`,onMount:d=>{d.querySelector('[data-no]').onclick=closeModal;d.querySelector('[data-yes]').onclick=()=>{closeModal();onConfirm();};}});}
